<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>msc</string>
		<string>mscgen</string>
	</array>
	<key>name</key>
	<string>Mscgen</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Comment</string>
			<key>match</key>
			<string>\#.*$</string>
			<key>name</key>
			<string>comment.line.mscgen</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(msc)\s+{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.msc.mscgen</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Encapsulating</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>msc.block.mscgen</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.arrow.mscgen</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Arrows</string>
					<key>match</key>
					<string>(\w+)\s*((-&gt;\*?)|(\*?&lt;-)|(=&gt;)|(&lt;=)|(=?&gt;&gt;)|(&lt;&lt;=?)|(-x)|(x-)|((a|r)?box)|note)\s*(\w+)</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>comment</key>
					<string>Attributes</string>
					<key>end</key>
					<string>\]</string>
					<key>name</key>
					<string>braces.meta.mscgen</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#attributes</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#optionselection</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>attributes</key>
		<dict>
			<key>match</key>
			<string>\b(label|URL|ID|IDURL|arcskip|linecolour|linecolor|textcolour|textcolor|textbgcolour|textbgcolor|arclinecolour|arclinecolor|arctextcolour|arctextcolor|arctextbgcolour|arctextbgcolor\b)</string>
			<key>name</key>
			<string>keyword.attribute.mscgen</string>
		</dict>
		<key>optionselection</key>
		<dict>
			<key>comment</key>
			<string>Possible options</string>
			<key>match</key>
			<string>\b(hscale|width|arcgradient|wordwraparcs\b)</string>
			<key>name</key>
			<string>keyword.option.mscgen</string>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>comment</key>
			<string>String</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.quoted.double.mscgen</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.mscgen</string>
	<key>uuid</key>
	<string>8c167ec3-61c7-4492-b9ed-900fc02ae4fd</string>
</dict>
</plist>
